language: node_js
node_js:
  - "node"
script:
  - yarn lint
  - yarn cover
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
  - node_modules